#!/bin/bash
# easy_install pip
python3 -m pip install virtualenv
cd /home/ec2-user/python-flask-service
python3 -m virtualenv environment
source environment/bin/activate
# pip install -r requirements.txt
python3 -m pip install supervisor
